name: hostgirls
version: 1

libraries:
- name: "lxml"
  version: "2.3.4"

cron:
- url: /updateBigChest
  schedule: "*/9 * * * *"

- url: /updateBlackStocking
  schedule: "*/10 * * * *"

- url: /updateCharmingLegs
  schedule: "*/11 * * * *"

- url: /updateHodgepodge
  schedule: "*/12 * * * *"

- url: /updateMeiZi
  schedule: "*/5 * * * *"

- url: /updateSmallBottom
  schedule: "*/11 * * * *"

- url: /updateSmallFresh
  schedule: "*/7 * * * *"
