name: hostgirls
version: 1

libraries:
- name: "lxml"
  version: "2.3.4"

cron:
- url: /updateBigChest
  schedule: "*/30 * * * *"

- url: /updateBlackStocking
  schedule: "*/25 * * * *"

- url: /updateCharmingLegs
  schedule: "*/20 * * * *"

- url: /updateHodgepodge
  schedule: "*/20 * * * *"

- url: /updateMeiZi
  schedule: "*/15 * * * *"

- url: /updateSmallBottom
  schedule: "*/25 * * * *"

- url: /updateSmallFresh
  schedule: "*/30 * * * *"
